-- Insert UC Universities into the database
-- This script adds all University of California campuses

INSERT INTO universities (id, name, slug, city, state, country, website, email_domains, type, coordinates, timezone) VALUES
(
    'uc-berkeley-id',
    'University of California, Berkeley',
    'berkeley',
    'Berkeley',
    'CA',
    'USA',
    'https://berkeley.edu',
    ARRAY['berkeley.edu'],
    'Public',
    point(-122.2585, 37.8715),
    'America/Los_Angeles'
),
(
    'uc-davis-id',
    'University of California, Davis',
    'davis',
    'Davis',
    'CA',
    'USA',
    'https://ucdavis.edu',
    ARRAY['ucdavis.edu'],
    'Public',
    point(-121.7405, 38.5382),
    'America/Los_Angeles'
),
(
    'uc-irvine-id',
    'University of California, Irvine',
    'irvine',
    'Irvine',
    'CA',
    'USA',
    'https://uci.edu',
    ARRAY['uci.edu'],
    'Public',
    point(-117.8443, 33.6405),
    'America/Los_Angeles'
),
(
    'uc-la-id',
    'University of California, Los Angeles',
    'ucla',
    'Los Angeles',
    'CA',
    'USA',
    'https://ucla.edu',
    ARRAY['ucla.edu'],
    'Public',
    point(-118.4452, 34.0689),
    'America/Los_Angeles'
),
(
    'uc-merced-id',
    'University of California, Merced',
    'merced',
    'Merced',
    'CA',
    'USA',
    'https://ucmerced.edu',
    ARRAY['ucmerced.edu'],
    'Public',
    point(-120.4829, 37.3665),
    'America/Los_Angeles'
),
(
    'uc-riverside-id',
    'University of California, Riverside',
    'riverside',
    'Riverside',
    'CA',
    'USA',
    'https://ucr.edu',
    ARRAY['ucr.edu'],
    'Public',
    point(-117.3234, 33.9731),
    'America/Los_Angeles'
),
(
    'uc-sandiego-id',
    'University of California, San Diego',
    'ucsd',
    'San Diego',
    'CA',
    'USA',
    'https://ucsd.edu',
    ARRAY['ucsd.edu'],
    'Public',
    point(-117.2340, 32.8801),
    'America/Los_Angeles'
),
(
    'uc-sf-id',
    'University of California, San Francisco',
    'ucsf',
    'San Francisco',
    'CA',
    'USA',
    'https://ucsf.edu',
    ARRAY['ucsf.edu'],
    'Public',
    point(-122.4194, 37.7749),
    'America/Los_Angeles'
),
(
    'uc-santabarbara-id',
    'University of California, Santa Barbara',
    'ucsb',
    'Santa Barbara',
    'CA',
    'USA',
    'https://ucsb.edu',
    ARRAY['ucsb.edu'],
    'Public',
    point(-119.6982, 34.4208),
    'America/Los_Angeles'
),
(
    'uc-santacruz-id',
    'University of California, Santa Cruz',
    'ucsc',
    'Santa Cruz',
    'CA',
    'USA',
    'https://ucsc.edu',
    ARRAY['ucsc.edu'],
    'Public',
    point(-122.0470, 36.9741),
    'America/Los_Angeles'
); 